# Generated by Django 3.2.20 on 2023-08-23 09:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('Burgers', 'Burgers'), ('Sides', 'Sides'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], default='Burgers', max_length=10)),
                ('item_image', cloudinary.models.CloudinaryField(default='menu_item_images/placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu_Item',
        ),
    ]
