# Generated by Django 3.2.20 on 2023-08-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menu_Item',
        ),
    ]
