# Generated by Django 3.2.20 on 2023-08-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_menu_menu_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationAdmin',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservation.reservation')),
            ],
            bases=('reservation.reservation',),
        ),
    ]
