# Generated by Django 3.2.20 on 2023-08-06 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservationadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_ItemAdmin',
            fields=[
                ('menu_item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservation.menu_item')),
            ],
            bases=('reservation.menu_item',),
        ),
    ]
