# Generated by Django 3.2.20 on 2023-08-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_menu_itemadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationadmin',
            name='reservation_ptr',
        ),
        migrations.DeleteModel(
            name='Menu_ItemAdmin',
        ),
        migrations.DeleteModel(
            name='ReservationAdmin',
        ),
    ]
