# Generated by Django 3.2.20 on 2023-08-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20230806_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='menu_item',
            name='category',
            field=models.CharField(choices=[('Burgers', 'Burgers'), ('Sides', 'Sides'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], default='Burgers', max_length=10),
        ),
    ]
