# Generated by Django 3.2.20 on 2023-08-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_reservation_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='approved',
        ),
    ]
