# Generated by Django 3.2.20 on 2023-08-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_remove_reservation_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu_Item',
        ),
    ]
